#ifndef FRONTEND_ASSETS_H
#define FRONTEND_ASSETS_H

static const char INDEX_HTML[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "  <meta charset=\"UTF-8\">\n"
    "  <title>Lambda Monitor</title>\n"
    "  <link rel=\"stylesheet\" href=\"/style.css\">\n"
    "</head>\n"
    "<body>\n"
    "  <nav>\n"
    "    <button data-tab=\"live\" class=\"tab-btn active\">Live</button>\n"
    "    <button data-tab=\"chart\" class=\"tab-btn\">Chart</button>\n"
    "    <button data-tab=\"settings\" class=\"tab-btn\">Settings</button>\n"
    "  </nav>\n"
    "\n"
    "  <section id=\"tab-live\" class=\"tab-panel active\">\n"
    "    <svg id=\"gauge\" viewBox=\"0 0 200 120\" width=\"300\">\n"
    "      <path d=\"M20,110 A80,80 0 0,1 76,35\" stroke=\"red\" stroke-width=\"12\" fill=\"none\"/>\n"
    "      <path d=\"M76,35 A80,80 0 0,1 124,35\" stroke=\"green\" stroke-width=\"12\" fill=\"none\"/>\n"
    "      <path d=\"M124,35 A80,80 0 0,1 180,110\" stroke=\"blue\" stroke-width=\"12\" fill=\"none\"/>\n"
    "      <line id=\"needle-fast\" x1=\"100\" y1=\"110\" x2=\"100\" y2=\"30\" stroke=\"black\" stroke-width=\"3\"/>\n"
    "      <line id=\"needle-slow\" x1=\"100\" y1=\"110\" x2=\"100\" y2=\"40\" stroke=\"gray\" stroke-width=\"2\"/>\n"
    "    </svg>\n"
    "    <p id=\"status-text\">Sensor warming up…</p>\n"
    "    <p>Switching frequency: <span id=\"switch-freq\">0</span> /min</p>\n"
    "    <div id=\"session-bar\" class=\"stacked-bar\"></div>\n"
    "    <div id=\"longterm-bar\" class=\"stacked-bar\"></div>\n"
    "    <button id=\"reset-btn\">Reset long-term statistics</button>\n"
    "  </section>\n"
    "\n"
    "  <section id=\"tab-chart\" class=\"tab-panel\">\n"
    "    <div id=\"chart\"></div>\n"
    "    <button id=\"freeze-btn\">Freeze</button>\n"
    "  </section>\n"
    "\n"
    "  <section id=\"tab-settings\" class=\"tab-panel\">\n"
    "    <form id=\"config-form\">\n"
    "      <label>u_min (mV) <input name=\"u_min_mv\" type=\"number\"></label>\n"
    "      <label>u_max (mV) <input name=\"u_max_mv\" type=\"number\"></label>\n"
    "      <label>u_lambda1 (mV) <input name=\"u_lambda1_mv\" type=\"number\"></label>\n"
    "      <label>deadband (mV) <input name=\"deadband_mv\" type=\"number\"></label>\n"
    "      <button type=\"submit\">Save</button>\n"
    "    </form>\n"
    "    <div id=\"wizard\">\n"
    "      <p>Live voltage: <span id=\"wizard-live-mv\">-</span> mV</p>\n"
    "      <button id=\"wizard-set-lambda1\">Take as λ=1</button>\n"
    "      <button id=\"wizard-set-min\">Take as u_min (lean)</button>\n"
    "      <button id=\"wizard-set-max\">Take as u_max (rich)</button>\n"
    "    </div>\n"
    "  </section>\n"
    "\n"
    "  <script src=\"/app.js\"></script>\n"
    "</body>\n"
    "</html>\n"
    "";

static const char STYLE_CSS[] =
    "body { font-family: sans-serif; margin: 0; padding: 1rem; }\n"
    "nav { display: flex; gap: 0.5rem; margin-bottom: 1rem; }\n"
    ".tab-btn.active { font-weight: bold; }\n"
    ".tab-panel { display: none; }\n"
    ".tab-panel.active { display: block; }\n"
    ".stacked-bar { display: flex; height: 1.5rem; width: 100%; margin: 0.5rem 0; overflow: hidden; border: 1px solid #ccc; }\n"
    ".bar-warmup { background: gray; }\n"
    ".bar-lean { background: red; }\n"
    ".bar-lambda1 { background: green; }\n"
    ".bar-rich { background: blue; }\n"
    "";

static const char APP_JS[] =
    "document.querySelectorAll('.tab-btn').forEach(btn => {\n"
    "  btn.addEventListener('click', () => {\n"
    "    document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));\n"
    "    document.querySelectorAll('.tab-panel').forEach(p => p.classList.remove('active'));\n"
    "    btn.classList.add('active');\n"
    "    document.getElementById('tab-' + btn.dataset.tab).classList.add('active');\n"
    "  });\n"
    "});\n"
    "\n"
    "function indexToAngle(index) {\n"
    "  return (index / 100) * 90;\n"
    "}\n"
    "\n"
    "function updateGauge(indexFast, indexSlow) {\n"
    "  const needleFast = document.getElementById('needle-fast');\n"
    "  const needleSlow = document.getElementById('needle-slow');\n"
    "  needleFast.setAttribute('transform', `rotate(${indexToAngle(indexFast)} 100 110)`);\n"
    "  needleSlow.setAttribute('transform', `rotate(${indexToAngle(indexSlow)} 100 110)`);\n"
    "}\n"
    "\n"
    "function renderStackedBar(elId, tWarmup, tLean, tLambda1, tRich) {\n"
    "  const total = tWarmup + tLean + tLambda1 + tRich;\n"
    "  const el = document.getElementById(elId);\n"
    "  el.innerHTML = '';\n"
    "  if (total === 0) return;\n"
    "  const segments = [\n"
    "    ['bar-warmup', tWarmup], ['bar-lean', tLean],\n"
    "    ['bar-lambda1', tLambda1], ['bar-rich', tRich],\n"
    "  ];\n"
    "  for (const [cls, seconds] of segments) {\n"
    "    const pct = (seconds / total) * 100;\n"
    "    if (pct <= 0) continue;\n"
    "    const div = document.createElement('div');\n"
    "    div.className = cls;\n"
    "    div.style.width = pct + '%';\n"
    "    el.appendChild(div);\n"
    "  }\n"
    "}\n"
    "\n"
    "let lastLiveMv = 0;\n"
    "\n"
    "const ws = new WebSocket(`ws://${location.host}/ws`);\n"
    "ws.onmessage = (event) => {\n"
    "  const data = JSON.parse(event.data);\n"
    "  updateGauge(data.index_fast, data.index_slow_avg);\n"
    "  document.getElementById('switch-freq').textContent = data.switches_per_min;\n"
    "  document.getElementById('status-text').textContent =\n"
    "    data.warmup_state === 0 ? 'Sensor warming up…' : 'Sensor ready';\n"
    "  document.getElementById('wizard-live-mv').textContent = data.index_fast;\n"
    "  lastLiveMv = data.index_fast;\n"
    "};\n"
    "\n"
    "async function refreshStats() {\n"
    "  const res = await fetch('/api/stats');\n"
    "  const s = await res.json();\n"
    "  renderStackedBar('session-bar', s.t_warmup_s, s.t_lean_s, s.t_lambda1_s, s.t_rich_s);\n"
    "  renderStackedBar('longterm-bar', s.t_warmup_s, s.t_lean_s, s.t_lambda1_s, s.t_rich_s);\n"
    "}\n"
    "setInterval(refreshStats, 2000);\n"
    "refreshStats();\n"
    "\n"
    "document.getElementById('reset-btn').addEventListener('click', async () => {\n"
    "  if (confirm('Reset long-term statistics? This cannot be undone.')) {\n"
    "    await fetch('/api/reset', { method: 'POST' });\n"
    "    refreshStats();\n"
    "  }\n"
    "});\n"
    "\n"
    "document.getElementById('config-form').addEventListener('submit', async (e) => {\n"
    "  e.preventDefault();\n"
    "  const form = new FormData(e.target);\n"
    "  const body = Object.fromEntries(form.entries());\n"
    "  await fetch('/api/config', { method: 'POST', body: JSON.stringify(body) });\n"
    "});\n"
    "\n"
    "document.getElementById('wizard-set-lambda1').addEventListener('click', () => {\n"
    "  document.querySelector('[name=u_lambda1_mv]').value = lastLiveMv;\n"
    "});\n"
    "document.getElementById('wizard-set-min').addEventListener('click', () => {\n"
    "  document.querySelector('[name=u_min_mv]').value = lastLiveMv;\n"
    "});\n"
    "document.getElementById('wizard-set-max').addEventListener('click', () => {\n"
    "  document.querySelector('[name=u_max_mv]').value = lastLiveMv;\n"
    "});\n"
    "";

#endif